### ISSUE TITLE
feature comparison with mpc autofill

### ISSUE THREAD

**Issue by ndepaola** [nathenxbrewer/ProxyFill#1]
g'day! this thread is meant to be a discussion rather than a bug report/feature request/etc, but it looks like github discussions isn't set up for this repo.

you're aware of https://github.com/chilli-axe/mpc-autofill - i'm reaching out to identify what specific use cases this project solves that mpc autofill does not & if there's potential for us to join forces on this.

i skimmed the repo briefly and to me it looks like the scope of this project is:
* proxyfill is specifically targeted at pokemon cards, where mpc autofill works with any card game (it just has some additional functionality that targets magic: the gathering)
* proxyfill targets files stored in google drive, so it's identical to mpc autofill in this respect
* this project targets drivethrucards while mpc autofill targets makeplayingcards. although it looks like the drivethrucards automation is not complete
* the two projects share a lot of dna as primarily being interactive card project editors, but it looks like mpc autofill is more mature in this respect
* proxyfill includes a tabular view for reviewing all images in the database
* proxyfill includes a system for requesting that a creator adds a specific image to their drive

so to me it seems there's a lot of overlap in what we're each trying to achieve. i'd be open to working together to add the following features to mpc autofill which would close the gap between the two projects:
* drivethrucards automation could be added to the mpc autofill desktop tool. this would be a decently large amount of work - my experience has been that writing selenium automation software like this is a righteous pain in the ass
* pokemon-specific game integrations could be added:
    * if pokemon has double-sided cards (i'm not sure, i'm not a pokemon tcg player), we can set up automatic matching of the back face when a user queries the front face
    * integrations with pokemon deckbuilding sites
* i'd be open to scoping the addition of an image request system, but my primary concern here is people spamming the form
* i'd be open to scoping the addition of a drive explorer page to encapsulate the functionality of your tabular view.

this'd benefit you by giving you access to a lot of functionality we've added over the years for free:
* a robust card search framework with rich filtering functionality and support for cardbacks & tokens
* adding cards to the project in multiple formats
* exporting cards from the project in multiple formats
* bulk card management
* double sided card management
* if your users are familiar with mpc autofill, they don't need to learn how to use a new piece of software

and would benefit mpc autofill by enabling the project to serve a wider audience. let me know what you think

**Comment by nathenxbrewer** [comment]
Hello there! Thanks for taking the time to reach out. I want to preface this by saying that I am definitely interested in joining forces on this effort. With that said, I'm unsure how we would be able to execute that seeing as how our solutions are both developed in a different stack. I'd love to set up a call where we could discuss this in more detail and figure out what that would look like. Here are my remarks in response to the points you made in your post: 

"_proxyfill is specifically targeted at pokemon cards, where mpc autofill works with any card game (it just has some additional functionality that targets magic: the gathering)_"
- My intention was to open up ProxyFill to work with any card game, with plans to develop for Lorcana next. I was unable to find a way to create projects for any other card game in mpcfill, even in the new beta so maybe I'm looking in the wrong place but I was not aware mpcfill could support other card games. 


"_proxyfill targets files stored in google drive, so it's identical to mpc autofill in this respect_"
-ProxyFill actually supports any direct link to an image. I am just using Google Drive for now, but the editor will render any direct link provided. 

"_this project targets drivethrucards while mpc autofill targets makeplayingcards. although it looks like the drivethrucards automation is not complete_"
-This was the main reason for developing ProxyFill, was to support DTC because MPC refuses to print pokemon cards. Selenium has proven to be a pain in the ass for the DTC automation and I'm pretty sure the issue is on DTC's end. I'd love to hop in a call and work through the dtc automation together. 

I absolutely agree that mpcfill is more mature and altogether a more polished app. I definitely do not want to be in direct competition with you and I hope we can come together on this as I think that would benefit the community the most. That being said, we'd need to work out how exactly I would be brought into the fold and what that looks like. My main concern is that we both develop in entirely different languages. The benefit of using Blazor as I have is that the web app can easily be ported to mobile and desktop using .net MAUI Blazor Hybrid approach. Please feel free to reach out to me and let's setup a meeting to go over everything. I look forward to working with you.

**Comment by ndepaola** [comment]
forgot to reply to this until now sorry!

> I'd love to set up a call where we could discuss this in more detail and figure out what that would look like.

sure, i'd be open to discussing this further over a call! discord might be easiest - my username is `chilli_axe`

> "_proxyfill is specifically targeted at pokemon cards, where mpc autofill works with any card game (it just has some additional functionality that targets magic: the gathering)_"
> 
>     * My intention was to open up ProxyFill to work with any card game, with plans to develop for Lorcana next. I was unable to find a way to create projects for any other card game in mpcfill, even in the new beta so maybe I'm looking in the wrong place but I was not aware mpcfill could support other card games.

what difficulties did you encounter with getting mpc autofill to work with pokemon? all you would need to do is upload your pokemon cards to google drive and index that drive in an instance of the backend.

just commenting briefly on the distinction between mpc autofill (the software project) and mpc fill (the magic: the gathering-specific deployment of the software project which i have no direct control over, though its name being so similar to the software project is pretty confusing 😅) - if you were to use mpc autofill for pokemon cards, it would be as its own backend instance running on its own server, not through mpcfill.

> "_proxyfill targets files stored in google drive, so it's identical to mpc autofill in this respect_" -ProxyFill actually supports any direct link to an image. I am just using Google Drive for now, but the editor will render any direct link provided.

understood - there's been some interest in the past in expanding mpc autofill to work with other image hosting services - i just haven't gotten around to adding integrations with those services yet. i don't really have a formal roadmap but had imagined that an AWS S3 integration would be up next. given that the mpc autofill database is meant to be populated automatically through folder crawling rather than by hand, i'm not sure if supporting direct links would fit in well.

> "_this project targets drivethrucards while mpc autofill targets makeplayingcards. although it looks like the drivethrucards automation is not complete_" -This was the main reason for developing ProxyFill, was to support DTC because MPC refuses to print pokemon cards. Selenium has proven to be a pain in the ass for the DTC automation and I'm pretty sure the issue is on DTC's end. I'd love to hop in a call and work through the dtc automation together.

sure that sounds good. i've actually never looked at DTC so not really sure what a selenium automation of their frontend would look like right now. for context - for MPC, i ended up reverse-engineering the javascript that drives their frontend and using their internal functions within my desktop tool code - so i'm not simulating a drag and drop event, for example, but using the MPC internal JS function that gets called when you execute a drag and drop.

> I absolutely agree that mpcfill is more mature and altogether a more polished app. I definitely do not want to be in direct competition with you and I hope we can come together on this as I think that would benefit the community the most. That being said, we'd need to work out how exactly I would be brought into the fold and what that looks like. My main concern is that we both develop in entirely different languages. The benefit of using Blazor as I have is that the web app can easily be ported to mobile and desktop using .net MAUI Blazor Hybrid approach. Please feel free to reach out to me and let's setup a meeting to go over everything. I look forward to working with you.

there is the matter of us working in different stacks yea and i'm sure neither of us is inclined to port our code to a different language & framework to suit the other 😅 for what it's worth, my nextjs frontend could be compiled into a desktop application with electron w/o too much hassle, but i haven't gone very far down this path just yet. idk how much value a mobile app would generate personally.

**Comment by nathenxbrewer** [comment]
I sent you a friend request on Discord. Let's get together on a call and see what we can come up with. Thanks for the replies. I'll close out this issue now.
